### ISSUE TITLE
Cannot start with Nextcloud 30 because of invalid PHP version

### ISSUE THREAD

**Issue by major-mayer** [skjnldsv/docker-nextcloud-dev#46]
When I try to run the server with Nextcloud 30 checked out, it returns the following error as soon as I interact with the CLI or website:
```
docker@2e7073600524:/var/www/nextcloud$ ./occ config
This version of Nextcloud requires at least PHP 8.1<br/>You are currently running 8.0.8. Please update your PHP version
```
This makes sense, given that the docker image hasn't been updated in 3 years: https://hub.docker.com/r/skjnldsv/nextcloud-dev

But I have seen that you have pushed a new (nightly) container image to your Github registry: https://github.com/skjnldsv/docker-nextcloud-dev/pkgs/container/docker-nextcloud-dev
So I tried swapping out the image and the server started again.
However, as soon as I want to interact with it, the following error is returned:
```
./occ --help
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2006] MySQL server has gone away in /var/www/nextcloud/lib/private/DB/Connection.php:227
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(452): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(410): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(317): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1315): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(187): Doctrine\DBAL\Connection->setNestTransactionsWithSavepoints(true)
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/src/DriverManager.php(197): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/nextcloud/lib/private/DB/ConnectionFactory.php(148): Doctrine\DBAL\DriverManager::getConnection(Object(SensitiveParameterValue), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/nextcloud/lib/private/Server.php(819): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet('OC\\DB\\Connectio...')
#11 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\DB\\Connectio...', true)
#12 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query('OC\\DB\\Connectio...', true)
#13 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map(Object(Closure), Array)
#15 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#16 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\DB\\Connectio...')
#17 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\DB\\Connectio...', true)
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query('OC\\DB\\Connectio...')
#19 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(175): OC\AppFramework\Utility\SimpleContainer->get('OC\\DB\\Connectio...')
#20 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#21 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#23 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...', true)
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query('OCP\\IDBConnecti...', true)
#25 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#26 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map(Object(Closure), Array)
#27 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#28 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#29 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...', true)
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query('OC\\Authenticati...', true)
#31 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#32 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map(Object(Closure), Array)
#33 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#34 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#35 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...', true)
#36 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query('OC\\Authenticati...', true)
#37 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#38 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map(Object(Closure), Array)
#39 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#40 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\Authenticati...')
#41 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...', true)
#42 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query('OC\\Authenticati...')
#43 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(175): OC\AppFramework\Utility\SimpleContainer->get('OC\\Authenticati...')
#44 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#45 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#46 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet('OC\\Authenticati...')
#47 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...', true)
#48 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query('OC\\Authenticati...')
#49 /var/www/nextcloud/lib/private/Server.php(497): OC\AppFramework\Utility\SimpleContainer->get('OC\\Authenticati...')
#50 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\Server->OC\{closure}(Object(OC\Server))
#51 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#52 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet('OC\\User\\Session')
#53 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\User\\Session', true)
#54 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query('OC\\User\\Session')
#55 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(175): OC\AppFramework\Utility\SimpleContainer->get('OC\\User\\Session')
#56 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#57 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#58 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet('OCP\\IUserSessio...')
#59 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IUserSessio...', true)
#60 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query('OCP\\IUserSessio...')
#61 /var/www/nextcloud/lib/private/Server.php(857): OC\AppFramework\Utility\SimpleContainer->get('OCP\\IUserSessio...')
#62 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\Server->OC\{closure}(Object(OC\Server))
#63 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#64 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#65 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\App\\AppManag...', true)
#66 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query('OC\\App\\AppManag...')
#67 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(175): OC\AppFramework\Utility\SimpleContainer->get('OC\\App\\AppManag...')
#68 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#69 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#70 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet('OCP\\App\\IAppMan...')
#71 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OCP\\App\\IAppMan...', true)
#72 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query('OCP\\App\\IAppMan...', true)
#73 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#74 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map(Object(Closure), Array)
#75 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#76 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve('OC\\AppFramework...')
#77 /var/www/nextcloud/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query('OC\\AppFramework...', true)
#78 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query('OC\\AppFramework...')
#79 /var/www/nextcloud/lib/public/Server.php(39): OC\AppFramework\Utility\SimpleContainer->get('OC\\AppFramework...')
#80 /var/www/nextcloud/lib/base.php(656): OCP\Server::get('OC\\AppFramework...')
#81 /var/www/nextcloud/lib/base.php(1132): OC::init()
#82 /var/www/nextcloud/console.php(28): require_once('/var/www/nextcl...')
#83 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
``` 

I haven't changed anything in the compose configuration, so the database username, password, etc. are still the same.
Still it looks like the authentication is not successful.
Here are the logs from the compose stack:
```
mysql-1      | 2024-08-29 10:18:59+00:00 [Warn] [Entrypoint]: /sys/fs/cgroup///memory.pressure not writable, functionality unavailable to MariaDB
mysql-1      | 2024-08-29 10:18:59+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db-1         | 2024-08-29 10:18:59: (debug) chassis-unix-daemon.c:121: we are the child: 13
db-1         | 2024-08-29 10:18:59: (critical) plugin proxy 0.8.5 started
db-1         | 2024-08-29 10:18:59: (debug) max open file-descriptors = 1073741816
db-1         | 2024-08-29 10:18:59: (message) proxy listening on port :3306
db-1         | 2024-08-29 10:18:59: (message) chassis-unix-daemon.c:136: [angel] we try to keep PID=13 alive
db-1         | 2024-08-29 10:18:59: (debug) chassis-unix-daemon.c:157: waiting for 13
db-1         | 2024-08-29 10:18:59: (message) added read/write backend: mysql:3306
mysql-1      | 2024-08-29 10:18:59+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.5.2+maria~ubu2404 started.
omgwtfssl-1 exited with code 0
php-1        | Host ip is 172.19.0.1
php-1        | 172.19.0.1       host.docker.internal
php-1        | 127.0.0.1        localhost
php-1        | ::1      localhost ip6-localhost ip6-loopback
php-1        | fe00::0  ip6-localnet
php-1        | ff00::0  ip6-mcastprefix
php-1        | ff02::1  ip6-allnodes
php-1        | ff02::2  ip6-allrouters
php-1        | 172.19.0.6       27ce3b3f2277
php-1        | 172.19.0.1       host.docker.internal
php-1        | [29-Aug-2024 10:18:59] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
php-1        | [29-Aug-2024 10:18:59] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
php-1        | [29-Aug-2024 10:18:59] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
php-1        | [29-Aug-2024 10:18:59] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
php-1        | [29-Aug-2024 10:18:59] NOTICE: fpm is running, pid 14
php-1        | [29-Aug-2024 10:18:59] NOTICE: ready to handle connections
mysql-1      | 2024-08-29 10:18:59+00:00 [Note] [Entrypoint]: MariaDB upgrade information missing, assuming required
mysql-1      | 2024-08-29 10:18:59+00:00 [Note] [Entrypoint]: MariaDB upgrade (mariadb-upgrade or creating healthcheck users) required, but skipped due to $MARIADB_AUTO_UPGRADE setting
mysql-1      | 2024-08-29 10:18:59 0 [Note] Starting MariaDB 11.5.2-MariaDB-ubu2404 source revision ea75a0b6009b0251e83193cd38c3974e36b65e06 server_uid boI2yEWnP+b4JlB7IyqfY5XtYeU= as process 1
mysql-1      | 2024-08-29 10:18:59 0 [Warning] --innodb-file-per-table is deprecated and will be removed in a future release
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: Compressed tables use zlib 1.3
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: Number of transaction pools: 1
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mysql-1      | 2024-08-29 10:18:59 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
mysql-1      | 2024-08-29 10:18:59 0 [Warning] mariadbd: io_uring_queue_init() failed with errno 95
mysql-1      | 2024-08-29 10:18:59 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: Completed initialization of buffer pool
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: End of log at LSN=1318471
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: Opened 3 undo tablespaces
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: log sequence number 1318471; transaction id 2051
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql-1      | 2024-08-29 10:18:59 0 [Note] Plugin 'FEEDBACK' is disabled.
mysql-1      | 2024-08-29 10:18:59 0 [Note] Plugin 'wsrep-provider' is disabled.
mysql-1      | 2024-08-29 10:18:59 0 [Warning] 'innodb-large-prefix' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
mysql-1      | 2024-08-29 10:18:59 0 [Warning] 'innodb-file-format' was removed. It does nothing now and exists only for compatibility with old my.cnf files.
mysql-1      | 2024-08-29 10:18:59 0 [Note] InnoDB: Buffer pool(s) load completed at 240829 10:18:59
web-1        | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
web-1        | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
web-1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
web-1        | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
web-1        | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
web-1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
web-1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
web-1        | /docker-entrypoint.sh: Configuration complete; ready for start up
web-1        | 2024/08/29 10:18:59 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:25
web-1        | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:25
web-1        | 2024/08/29 10:18:59 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:26
web-1        | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:26
web-1        | 2024/08/29 10:18:59 [warn] 1#1: duplicate extension "js", content type: "text/javascript", previous content type: "application/javascript" in /etc/nginx/conf.d/default.conf:88
web-1        | nginx: [warn] duplicate extension "js", content type: "text/javascript", previous content type: "application/javascript" in /etc/nginx/conf.d/default.conf:88
web-1        | 2024/08/29 10:18:59 [notice] 1#1: using the "epoll" event method
web-1        | 2024/08/29 10:18:59 [notice] 1#1: nginx/1.27.1
web-1        | 2024/08/29 10:18:59 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14) 
web-1        | 2024/08/29 10:18:59 [notice] 1#1: OS: Linux 6.6.47-1-MANJARO
web-1        | 2024/08/29 10:18:59 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
web-1        | 2024/08/29 10:18:59 [notice] 1#1: start worker processes
web-1        | 2024/08/29 10:18:59 [notice] 1#1: start worker process 21
web-1        | 2024/08/29 10:18:59 [notice] 1#1: start worker process 22
web-1        | 2024/08/29 10:18:59 [notice] 1#1: start worker process 23
web-1        | 2024/08/29 10:18:59 [notice] 1#1: start worker process 24
web-1        | 2024/08/29 10:18:59 [notice] 1#1: start worker process 25
web-1        | 2024/08/29 10:18:59 [notice] 1#1: start worker process 26
mysql-1      | 2024-08-29 10:19:00 0 [Note] Server socket created on IP: '0.0.0.0'.
mysql-1      | 2024-08-29 10:19:00 0 [Note] Server socket created on IP: '::'.
mysql-1      | 2024-08-29 10:19:00 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
mysql-1      | 2024-08-29 10:19:00 0 [Note] mariadbd: ready for connections.
mysql-1      | Version: '11.5.2-MariaDB-ubu2404'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
db-1         | 2024-08-29 10:19:06: (critical) network-mysqld-packet.c:1285: protocol 10, but version number out of range
mysql-1      | 2024-08-29 10:19:06 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.19.0.5' (This connection closed normally without authentication)
mysql-1      | 2024-08-29 10:19:06 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'unauthenticated' host: '172.19.0.5' (This connection closed normally without authentication)
mysql-1      | 2024-08-29 10:19:06 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: '172.19.0.5' (This connection closed normally without authentication)
mysql-1      | 2024-08-29 10:19:06 6 [Warning] Aborted connection 6 to db: 'unconnected' user: 'unauthenticated' host: '172.19.0.5' (This connection closed normally without authentication)
mysql-1      | 2024-08-29 10:19:06 7 [Warning] Aborted connection 7 to db: 'unconnected' user: 'unauthenticated' host: '172.19.0.5' (This connection closed normally without authentication)
```

Any ideas, how I can fix my development stack again?

**Comment by skjnldsv** [comment]
Switch your image to `ghcr.io/skjnldsv/docker-nextcloud-dev`
https://github.com/skjnldsv/docker-nextcloud-dev/pkgs/container/docker-nextcloud-dev

**Comment by skjnldsv** [comment]
Share your docker-compose please?

**Comment by major-mayer** [comment]
Thanks for the very quick response.
Sure, here you go:
```yaml
version: '2'

volumes:
    mariadb:
    web-certs:

networks:
    nextcloud:

services:
    mysql:
        image: mariadb
        restart: "no"
        # https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb-large-prefix --innodb-file-per-table --innodb-file-format=barracuda --skip-innodb-read-only-compressed
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        networks:
            - nextcloud

    # DB proxy: watch docker logs to see all sql queries
    # `docker-compose logs -f db`
    db:
        build: ./docker-mysql-proxy
        restart: "no"
        volumes:
            - ./docker-mysql-proxy/log.lua:/opt/mysql-proxy/conf/log.lua:ro
            - ./docker-mysql-proxy/main.lua:/opt/mysql-proxy/conf/main.lua:ro
        environment:
            PROXY_DB_PORT: 3306
            REMOTE_DB_HOST: mysql
            REMOTE_DB_PORT: 3306
            LUA_SCRIPT: "/opt/mysql-proxy/conf/main.lua"
            LOG_FILE: "/tmp/mysql.log"
        depends_on:
            - mysql
        networks:
            - nextcloud

    php:
        image: ghcr.io/skjnldsv/docker-nextcloud-dev 
        volumes:
            - ./server:/var/www/nextcloud
            - ./data:/var/www/nextcloud/data
            - ./apps2:/var/www/nextcloud/apps2
            # COMMENT IF YOU WANT FULL CONTROL ON THE NEXTCLOUD INITIAL SETUP
            - ./config/autoconfig.php:/var/www/nextcloud/config/autoconfig.php:ro
            - ./config/debug.config.php:/var/www/nextcloud/config/debug.config.php:ro
            # COMMENT TO DISABLE REDIS
            - ./config/redis.config.php:/var/www/nextcloud/config/redis.config.php:ro
            # UNCOMMENT TO ENABLE SMTP
            # - ./config/smtp.config.php:/var/www/nextcloud/config/smtp.config.php:ro
            - ./config/apps.config.php:/var/www/nextcloud/config/apps.config.php:ro
        restart: "no"
        environment:
            # use mysql instead of db if you disabled the db proxy
            - MYSQL_HOST=db
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            # comment if redis is disabled
            - REDIS_HOST=redis
            - PHP_IDE_CONFIG='serverName=cli'
            - NEXTCLOUD_DATA_DIR=/var/www/nextcloud/data
            # UNCOMMENT TO ENABLE XDEBUG 
            # host.docker.internal is initiated on the container on each start
            # and bound to the host ip
            - XDEBUG_CONFIG=remote_host=host.docker.internal remote_autostart=On remote_enable=On idekey=XDEBUG remote_log=/tmp/xdebug.log remote_port=9999
            - PHP_XDEBUG_ENABLED=1
            - PHP_XDEBUG_IDE_KEY=XDEBUG
        depends_on:
            # use mysql instead of db if you disabled the db proxy
            - db
            # comment if redis is disabled
            - redis
        networks:
            - nextcloud

    web:
        image: nginx
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./server:/var/www/nextcloud
            - ./apps2:/var/www/nextcloud/apps2
            - ./nextcloud.conf:/etc/nginx/conf.d/default.conf:ro
            - web-certs:/etc/nginx/certs:ro
        restart: "no"
        networks:
            - nextcloud
        depends_on:
            - php

    omgwtfssl:
        image: paulczar/omgwtfssl
        volumes:
            - web-certs:/certs
        environment:
            # CHANGE IT TO YOU DOMAIN NAME
            - SSL_SUBJECT=dev.domain.com
        networks:
            - nextcloud

    # UNCOMMENT TO ENABLE PHPMYADMIN
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin:latest
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=rootpassword
    #         - MYSQL_PASSWORD=password
    #         - MYSQL_DATABASE=nextcloud
    #         - MYSQL_USER=nextcloud
    #         # use mysql instead of db if you disabled the db proxy
    #         - PMA_HOST=db
    #     restart: always
    #     networks:
    #         - nextcloud
    #     depends_on:
    #         # use mysql instead of db if you disabled the db proxy
    #         - db
    
    # UNCOMMENT TO ENABLE SMTP
    # smtp:
    #     image: namshi/smtp
    #     restart: always
    #     networks:
    #         - nextcloud

    # COMMENT TO DISABLE REDIS
    redis:
        image: redis:latest
        restart: "no"
        networks:
            - nextcloud

```

I added a few lines to prevent the containers from restarting, which is something I don't want on my dev machine, and swapped the php image, but apart from this, it should be the same as your base.
